PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/0360bb830dc77ceaf613c324cafa0f8afc084e27

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/9331fda0d7f7220de33982e8a641c671b1f09c8e) in current PX4/master (1484dfed6a8200781865034d812450936388efc4)
https://github.com/PX4/NuttX/compare/9331fda0d7f7220de33982e8a641c671b1f09c8e...0360bb830dc77ceaf613c324cafa0f8afc084e27

0360bb830d (HEAD, origin/master) Merge branch 'master' of bitbucket.org:nuttx/nuttx
9202df8a27 Merge branch 'master' of github.com:apache/incubator-nuttx
981d7004fa Remove inet_setipid since nobody use it
534640e561 Merge branch 'master' of bitbucket.org:nuttx/nuttx
828c650aee Merge branch 'master' of github.com:apache/incubator-nuttx
5d5897c309 Merge pull request #41 from wingunder/wingunder_fix_compilation_bug_irq_f7_h7
00df2f0fe2 Fixed a compilation error, with irq debugging for stm32f7 and stm32h7 archs.
c9893dc989 Merge branch 'master' of github.com:apache/incubator-nuttx
7179f2940d Merge pull request #40 from xiaoxiang781216/fix-shell-script-format
3b9efc95a2 Format all shell scripts in tools folder

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/74ba8ff20215d6e8a83861b9cba963d5f5331048

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (1484dfed6a8200781865034d812450936388efc4)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...74ba8ff20215d6e8a83861b9cba963d5f5331048

74ba8ff2 (HEAD -> master, origin/master) Merge pull request #5 from xiaoxiang781216/fix-void-cast
f00b4e6f Merge pull request #4 from xiaoxiang781216/fix-suffix
85715845 Unify the void cast usage
6a65664c Application.mk remove _main suffix from REGLIST
73e1696e Merge pull request #3 from xiaoxiang781216/builtin
7a645baa Add .updated target to handle the no builtin app case correctly
8c8c4813 fix builtin_list.c:58:10: fatal error: builtin_proto.h: No such file or directory (#2)
64bc8f5b Run all .c and .h files modified in last PR through nxstyle.
49c99750 Wapi simplify (#1)
0536c5b5 apps/nshlib/nsh_parse.c:  Correct an error found in build testing.  Commit 2a462c78aa5f4ea6dc374eedd86bc85f9f79a0c4 was insufficient.  It was a mistake to revert Xiang's change of commit 9defae8af641752506d92b72ea68c8f94d24d580.  But we are on a different vector now.